# Generated by Django 6.1.1 on 2026-09-29 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0002_quiz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
